env:
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION="PyFunceble"

language: generic

jobs:
  include:
    - os: linux
      dist: bionic
      name: "Test with Python 3.8.0 under Ubuntu Bionic"
      env: PYTHON_VERSION="3.8.0"
    - os: osx
      osx_image: xcode9.4
      name: "Test with Python 3.8.0 under macOS 10.13"
      env: PYTHON_VERSION="3.8.0"
    - os: linux
      dist: bionic
      name: "Test with Python 3.7.4 under Ubuntu Bionic"
      env: PYTHON_VERSION="3.7.4"
    - os: osx
      osx_image: xcode9.4
      name: "Test with Python 3.7.4 under macOS 10.13"
      env: PYTHON_VERSION="3.7.4"
    - os: linux
      dist: bionic
      name: "Test with Python 3.7.3 under Ubuntu Bionic"
      env: PYTHON_VERSION="3.7.3"
    - os: osx
      osx_image: xcode9.4
      name: "Test with Python 3.7.3 under macOS 10.13"
      env: PYTHON_VERSION="3.7.3"
    - os: linux
      dist: bionic
      name: "Test with Python 3.6.9 under Ubuntu Bionic"
      env: PYTHON_VERSION="3.6.9"
    - os: osx
      osx_image: xcode9.4
      name: "Test with Python 3.6.9 under macOS 10.13"
      env: PYTHON_VERSION="3.6.9"
    - os: linux
      dist: bionic
      name: "Test with Python 3.6.8 <under Ubuntu Bionic"
      env: PYTHON_VERSION="3.6.8"
    - os: osx
      osx_image: xcode9.4
      name: "Test with Python 3.6.8 under macOS 10.13"
      env: PYTHON_VERSION="3.6.8"

matrix:
  fast_finish: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python -VV
  - pip --version
  - pip install pylint coverage coveralls codacy-coverage cffi

script:
  - pip install -e .
  - coverage run setup.py test
  - coverage xml # Needed for codacy.
  - echo "Lint PyFunceble" && pylint PyFunceble
  - echo "Lint tests" && pylint tests
  - PyFunceble -v
  - PyFunceble --clean
  - PyFunceble --clean-all
  - rm -R output && PyFunceble --directory-structure && ls -al output
  - PyFunceble -t 3 -ex -d github.com --dns 1.1.1.1 1.0.0.1
  - PyFunceble -t 3 -ex -s -f .travis/lists/simple -m --dns 1.1.1.1 1.0.0.1
  - PyFunceble -t 3 -ex --syntax -f .travis/lists/simple -m --dns 1.1.1.1 1.0.0.1
  - PyFunceble -t 3 -ex -f .travis/lists/simple --json --plain -m --dns 1.1.1.1 1.0.0.1
  - PyFunceble -t 3 -ex -f .travis/lists/simple -m --dns 1.1.1.1 1.0.0.1  # Normally, all inactive are not tested anymore.
  - PyFunceble -t 3 -ex --database -f .travis/lists/simple  -m  --dns 1.1.1.1 1.0.0.1 # And they will be retested.
  - PyFunceble -t 3 -ex --database --filter ".info$" -f .travis/lists/simple -m --dns 1.1.1.1 1.0.0.1  # Only .info domains should be tested.
  - PyFunceble -t 3 -ex --adblock -a -f .travis/lists/adblock -m --dns 1.1.1.1 1.0.0.1
  - PyFunceble -t 3 -ex --link https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts -m --dns 1.1.1.1 1.0.0.1
  - python .travis/complementary/basic_example.py
  - python .travis/complementary/basic_example_syntax.py
  - python .travis/complementary/advanced_example.py
  - python .travis/complementary/loop_example.py
  - python .travis/complementary/custom_configuration.py
  - python .travis/complementary/api_file_generation.py

after_success:
  - python-codacy-coverage -r coverage.xml
  - coveralls

deploy:
  provider: pypi
  user: funilrys
  password:
    secure: IG1FlVINvTCO7jscSz4aQMRABBcZVFGNBfDB0giAhtNV/Nr98jSyLZXETx7yquD93dFZpL58HXcPRxoa3hemyBLcTc0ATMsNBM48IrN3xaxfPytlQQn7aocKdZLAMbriCo7CO4x4O00lu3Cx2tAZtZMaDGYN+KpWIR9V+dXF1hHLj7owilko3YVXiXXamlOZmkdv28PcACQlJ7QLLYxTY3o/LuLrCOvo3zc+Ao0JfKpOv9Fm41keUS51Ek5QWXFaO7VNho6CXV7/5rJbF9w1flkM7GEUH78pjs+KpwBV7auwFYMerYPq5GVPiL117y9ojXxfF+B1qY1flreugCgSRJQKhzvfgSlgGhM93GG2yPpQu6LGIIZJ0MMcXldheY1JOzVMddXYbFTeG3j+/0a9EF47G9ZUeCiY3uCmaqaIuMvuby+Ze0XsHqrOkN+uALtgmrJuhDgiJvY1+qAIo56jBcaTYcOs+xqkFbqviltNjqriH3uFRhXZUpVQchd49eq6m+OyEu4jcYH9Pn1qHdwKBKU/KCRbYy9zAj5gso/HrSRaMrjMGUcdlzNEWKHVstnBPIq+9xnZ5Zeb7ev6i2vTH3WVHQoAFRGvNv/K7+zRMt0iDK2H9SCg3mi4v1c/JwUuY6Oht/PXwbbJ8sAIVAs+3P+FrEBIjkkbtjjPDHaA9rg=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    all_branches: true
    condition: "${TRAVIS_BRANCH} =~ ^dev|master$"

notifications:
  on_success: change
  on_failure: always
